spring.application.name=SAPA

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

server.port=${PORT:8080}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

logging.level.org.hibernate.SQL=ERROR
logging.level.org.springframework.web.socket=ERROR

spring.sql.init.mode=always

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.expiration=3600000
jwt.refresh-expiration=604800000
jwt_secret=${JWT_SECRET}
access_token=${ACCESS_TOKEN}

mailtrap.api.token=${MAILTRAP_API_TOKEN}
mailtrap.api.inbox-id=4719169
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true