spring.application.name=SAPA

spring.datasource.url=jdbc:mysql://localhost:3306/sapa
spring.datasource.username=root
spring.datasource.password=root

server.port=${PORT:8080}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

logging.level.org.hibernate.SQL=ERROR
logging.level.org.springframework.web.socket=ERROR

spring.sql.init.mode=always

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.expiration=3600000
jwt.refresh-expiration=604800000
jwt_secret=EstaEsUnaClaveSecretaSuperSeguraYMuyLargaParaSapaApi2026Sininonizados
access_token=mi-access-token-secreto-largo

mailtrap.api.token=68dbab7b790848e9e1712f3bcbcb569c
mailtrap.api.inbox-id=4719169
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${e9f68f17f4376a}
spring.mail.password=${74fa259d556a83}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true