package com.example.SAPA.security.enums;

public enum Permit {

    // SEGUIMIENTO
    SEGUIMIENTO_SOLICITAR,
    SEGUIMIENTO_GESTIONAR,
    SEGUIMIENTO_DISOLVER,

    // CHAT
    CHAT_ENVIAR,
    CHAT_LEER,
    CHAT_SUBIR_ADJUNTOS,

    // CUESTIONARIO
    CUESTIONARIO_CREAR,
    CUESTIONARIO_EDITAR,
    CUESTIONARIO_ELIMINAR,
    CUESTIONARIO_LEER,
    CUESTIONARIO_RESPONDER,

    // CONSEJO
    CONSEJO_PUBLICAR,
    CONSEJO_EDITAR,
    CONSEJO_ELIMINAR,
    CONSEJO_LEER,

    // FORO
    FORO_CREAR,
    FORO_EDITAR,
    FORO_ELIMINAR,
    FORO_LEER,
    FORO_FAVORITO,

    // POST
    POST_CREAR,
    POST_EDITAR,
    POST_ELIMINAR,
    POST_LEER,

    // CONTENIDO
    CONTENIDO_REPORTAR,
    CONTENIDO_MODERAR,

    // TURNO
    TURNO_REDIRECCIONAR
}
