package com.example.SAPA.security.enums;

public enum Permit {

    SEGUIMIENTO_SOLICITAR,
    SEGUIMIENTO_GESTIONAR,
    SEGUIMIENTO_DISOLVER,
    CHAT_ENVIAR,
    CHAT_LEER,
    CHAT_SUBIR_ADJUNTOS,
    CUESTIONARIO_GESTIONAR,
    CUESTIONARIO_LEER,
    CONSEJO_PUBLICAR,
    CONSEJO_LEER,
    FORO_ABM,
    FORO_LEER,
    FORO_FAVORITO,
    POST_ABM,
    POST_LEER,
    CONTENIDO_REPORTAR,
    CONTENIDO_MODERAR,
    TURNO_REDIRECCIONAR
}
