INSERT INTO speciality (name) VALUES 
('Alergología e Inmunología'),
('Anestesiología'),
('Angiología y Cirugía Vascular'),
('Cardiología'),
('Cirugía Cardiovascular'),
('Cirugía General'),
('Cirugía Maxilofacial'),
('Cirugía Plástica, Estética y Reparadora'),
('Cirugía Pediátrica'),
('Cirugía Torácica'),
('Dermatología'),
('Endocrinología y Nutrición'),
('Estomatología'),
('Gastroenterología / Aparato Digestivo'),
('Genética Médica'),
('Geriatría'),
('Ginecología y Obstetricia'),
('Hematología y Hemoterapia'),
('Infectología'),
('Inmunología'),
('Medicina del Deporte'),
('Medicina del Trabajo'),
('Medicina de Urgencias y Emergencias'),
('Medicina Familiar y Comunitaria'),
('Medicina Física y Rehabilitación'),
('Medicina Intensiva / Intensivista'),
('Medicina Interna'),
('Medicina Nuclear'),
('Medicina Preventiva y Salud Pública'),
('Nefrología'),
('Neumología'),
('Neurocirugía'),
('Neurofisiología Clínica'),
('Neurología'),
('Nutriología'),
('Oftalmología'),
('Oncología Médica'),
('Oncología Radioterápica'),
('Otorrinolaringología'),
('Pediatría'),
('Proctología'),
('Psiquiatría'),
('Reumatología'),
('Traumatología y Ortopedia'),
('Urología');